server:
  port: ${PORT:8888}

info:
  component: Config Server

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO:http://git.dev.sicoobpr.com.br/infrastructure/configuration.git}
          username: ${GIT_USER:docker}
          password: ${GIT_PASSWORD:Sicoob2009}