server:
  port: ${PORT:8888}

info:
  component: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO:https://github.com/thbono/apps-config.git}

management:
  security:
    enabled: false