server:
  port: ${PORT:8888}
  context-path: ${CONTEXT_PATH:/}

info:
  component: config-server
  version: 2.0

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO:https://github.com/thbono/apps-config.git}
          username: ${GIT_USER:}
          password: ${GIT_PASSWORD:}

management:
  security:
    enabled: false